import React from 'react';
import Navigation from '../../components/Layout/Navigation';
import Head from 'next/head';
import { FaFacebook, FaInstagram, FaTiktok, FaYoutube, FaLinkedin } from 'react-icons/fa';
import Footer from '../../components/Layout/Footer';
const index = () => {
  return (
    <div>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <section className="text-gray-600 body-font relative">
        <div className="container px-5 py-24 mx-auto flex sm:flex-nowrap flex-wrap">
          <div className="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
            <iframe
              className="absolute inset-0"
              style={{ filter: 'grayscale(1) contrast(1.2) opacity(0.4)' }}
              title="map"
              marginHeight="0"
              marginWidth="0"
              scrolling="no"
              src="https://maps.google.com/maps?width=100%&height=600&hl=en&q=casablnca+(My%20Business%20Name)&ie=UTF8&t=&z=14&iwloc=B&output=embed"
              width="100%"
              height="100%"
              frameBorder="0"
            ></iframe>
            <div className="bg-white relative flex flex-wrap py-6 rounded shadow-md">
              <div className="lg:w-1/2 px-6">
                <h2 className="title-font font-semibold text-gray-900 tracking-widest text-xs">ADDRESS</h2>
                <p className="mt-1">
                  Casablnca Morocco Photo booth tattooed prism, portland taiyaki hoodie neutra typewriter
                </p>
              </div>
              <div className="lg:w-1/2 px-6 mt-4 lg:mt-0">
                <h2 className="title-font font-semibold text-gray-900 tracking-widest text-xs">EMAIL</h2>
                <a className="text-blue-500 leading-relaxed">example@africafeedandfood.com</a>
                <h2 className="title-font font-semibold text-gray-900 tracking-widest text-xs mt-4">PHONE</h2>
                <p className="leading-relaxed">+212-000-0000</p>
              </div>
            </div>
          </div>

          <div className="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0">
            <h3 className="text-3xl text-center">Join-us</h3>
            <div className="flex  justify-center  ">
              <button className="text-lg text-neutral-content m-1 my-2">
                <FaFacebook className="text-3xl fill-gray-800 text-gary-800" />
              </button>

              <button className="text-3xl fill-gray-800 text-neutral-content m-1 my-2">
                <FaInstagram className="text-3xl fill-gray-800 text-gary-800" />
              </button>

              <button className="text-3xl fill-gray-800 text-neutral-content m-1 my-2">
                <FaTiktok className="text-3xl fill-gray-800 text-gary-800" />
              </button>

              <button className="text-3xl fill-gray-800 text-neutral-content m-1 my-2">
                <FaYoutube className="text-3xl fill-gray-800 text-gary-800" />
              </button>
              <button className="text-3xl fill-gray-800 text-neutral-content m-1 my-2">
                <FaLinkedin className="text-3xl fill-gray-800 text-gary-800" />
              </button>
            </div>
            <h2 className="text-gray-900 text-lg mb-1 font-medium title-font">Contact us</h2>
            <p className="leading-relaxed mb-5 text-gray-600"></p>

            <div className="relative mb-4">
              <label htmlFor="name" className="leading-7 text-sm text-gray-600">
                Name
              </label>
              <input
                type="text"
                id="name"
                name="name"
                className="w-full bg-white rounded border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
              />
            </div>
            <div className="relative mb-4">
              <label htmlFor="email" className="leading-7 text-sm text-gray-600">
                Email
              </label>
              <input
                type="email"
                id="email"
                name="email"
                className="w-full bg-white rounded border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"
              />
            </div>
            <div className="relative mb-4">
              <label htmlFor="message" className="leading-7 text-sm text-gray-600">
                Message
              </label>
              <textarea
                id="message"
                name="message"
                className="w-full bg-white rounded border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"
              ></textarea>
            </div>
            <button className="text-gray-800  bg-yellow-500 border-0 py-2 px-6 focus:outline-none hover:bg-blue-600 rounded text-lg font-bold">
              Button
            </button>
            <p className="text-xs text-gray-500 mt-3">
              Chicharrones blog helvetica normcore iceland tousled brook viral artisan.
            </p>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
};

export default index;
