import Head from 'next/head';
// import Image from 'next/image';
// import Carousel from '../components/Carousel';
import Footer from '../components/Layout/Footer';
import Navigation from '../components/Layout/Navigation';
import 'react-loading-skeleton/dist/skeleton.css';
import Skeleton from 'react-loading-skeleton';
import OurBrands from '../components/OurBrands';
import { motion } from 'framer-motion';
import { FaQuoteRight, FaQuoteLeft } from 'react-icons/fa';
import HAJMOHAMEDESSALHI_IMG from '../../public/images/HAJ-MOHAMED-ESSALHI.jpg';
import Media from '../components/Media';
import OurValues from '../components/OurValues';
import HomeSlider from '../components/HomeSlider';
import Image from 'next/image';
const cardVariantsRight = {
  offscreen: {
    //  x: 300,
    y: 120,
    opacity: 0.3,
  },
  onscreen: {
    // x: 0,
    y: 0,
    opacity: 1,
    transition: {
      type: 'spring',
      bounce: 0.5,
      duration: 2,
    },
  },
};

const variantMoveToRight = {
  offscreen: {
    // x: -300,
    y: 120,
    opacity: 0.3,
  },
  onscreen: {
    // x: 0,
    opacity: 1,
    y: 0,
    transition: {
      type: 'spring',
      bounce: 0.5,
      duration: 2,
    },
  },
};
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      {/* <Carousel /> */}
      <HomeSlider />
      {/* <Skeleton containerClassName="h-90" height={600} /> */}
      <motion.section
        className="container px-16 m-auto "
        initial="offscreen"
        whileInView="onscreen"
        viewport={{ once: true, amount: 0.8 }}
      >
        <section className="grid lg:grid-cols-6  lg:gap-x-10 ">
          <motion.div className="col-span-2 p-10 self-center" variants={variantMoveToRight}>
            <img src="./images/BestPract.png" width="500" alt="" />
          </motion.div>
          <motion.div className="col-span-4 flex flex-col lg:py-28 " variants={cardVariantsRight}>
            <h1 className="text-5xl text-yellow-500 font-bold m-2 p-2 px-4  pt-10 leading-normal">
              Fulfilling safely and effectively all households needs...
            </h1>
            <p className="text-3xl m-2 px-4  py-4  leading-normal  text-gray-700   border-l-4 ">
              Our practices have been governed by integrity, honesty, fair dealing and full compliance with all
              applicable laws.
            </p>
          </motion.div>
        </section>
      </motion.section>
      <motion.section
        className="container px-16 lg:py-28 m-auto  bg-yellow-300  h-full"
        initial="offscreen"
        whileInView="onscreen"
        viewport={{ once: true, amount: 0.8 }}
      >
        <section className="grid lg:grid-cols-6  lg:gap-x-10 drop-shadow-xl ">
          <motion.div
            className="col lg:col-span-2 p-10  image  self-center m-auto justify-self-center"
            variants={variantMoveToRight}
          >
            {/* <Skeleton containerClassName="h-10  m-auto  rounded-3xl " height={300} width={400} /> */}
            <Image src={HAJMOHAMEDESSALHI_IMG} height={300} width={400} alt="HAJ MOHAMED ESSALHI" />
          </motion.div>
          <motion.div className="col lg:col-span-4 flex flex-col m-auto" variants={cardVariantsRight}>
            <div className="flex m-auto  py-4">
              <FaQuoteLeft className="text-6xl basis-2/5 drop-shadow-xl " />
              <div className="text-3xl  py-6  font-bold leading-normal  text-gray-700 flex-auto   text-center self-center">
                Two concepts are essentiels in life are passion in achievement in every thing we do and loyalty in
                relationships
                <p className="text-sm col-span-1 py-4">
                  Mohamed Essalhi <br />
                  <span>Founder</span>
                </p>
              </div>
              <FaQuoteRight className="text-6xl self-end basis-2/5 drop-shadow-xl " />
            </div>
          </motion.div>
        </section>
      </motion.section>
      {/* <LogoCarousel /> */}
      <OurValues />
      <OurBrands />

      <Media />

      <Footer />
    </div>
  );
}
