import React from 'react';
import Navigation from '../../components/Layout/Navigation';
import Head from 'next/head';
import Footer from '../../components/Layout/Footer';
import { ImFilesEmpty } from 'react-icons/im';
const Media = () => {
  return (
    <div>
      <Head>
        <title>Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <section className="container ">
        <div className="m-auto p-20  text-center h-96 rounded-md shadow-lg">
          <div className="text-center ring-lg p-4 mx-auto w-16 h-16 p-2 rounded-full bg-yellow-200 my-2">
            <ImFilesEmpty className="text-center text-3xl" />
          </div>
          <h2 className="text-3xl font-bold ">We are working on it, It will be available soon </h2>
          <p></p>
        </div>
      </section>
      <Footer />
    </div>
  );
};

export default Media;
